name: 'Delete Prefect Cloud execution layer on Google Cloud Run'
branding:
  icon: cloud
  color: yellow
inputs:
  prefect_api_key:
    description: 'Prefect Cloud API key'
    required: true
  prefect_api_url:
    description: 'Prefect Cloud API URL'
    required: true
  region:
    description: 'GCP region'
    required: false
    default: 'us-central1'
  zone:
    description: 'GCP region with the zone'
    required: false
    default: 'us-central1-a'
  machine_type:
    description: 'GCP Compute Engine instance type'
    required: false
    default: 'e2-micro'
  bucket_suffix:
    description: Postfix for GCS bucket name
    required: true
    default: "raw-crypto-data"
    type: string
  dataset_name:
    description: BigQuery dataset name
    required: true
    default: "crypto_data"
    type: string
  machine_name:
    description: 'GCP Compute Engine instance name'
    required: false
    default: "binance-transactions"
  gcp_credentials_json:
    description: 'Content of the Service Account JSON key file'
    required: true
runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ inputs.gcp_credentials_json }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # - id: terminate-vm
    #   name: Terminate existing VM instances
    #   run: gcloud compute instances delete "${{ inputs.machine_name }}" --zone "${{ inputs.zone }}" --quiet --verbosity none
    #   shell: bash

    - id: delete-ar
      name: Delete Artifact Repository
      run: gcloud artifacts repositories delete ${{ inputs.artifact_repository }} --quiet --verbosity none
      shell: bash
    
    - id: delete-bucket
      name: Delete Cloud Storage bucket
      run: gcloud storage rm --recursive gs://$GCP_PROJECT-${{ inputs.bucket_suffix }}/
      shell: bash

    - id: delete-dataset
      name: Delete BigQuery dataset
      run: bq rm -r -f $GCP_PROJECT:${{ inputs.dataset_name }}
      shell: bash


  
