name: 'Prefect Cloud execution layer on Google Cloud Run'
branding:
  icon: cloud
  color: yellow
description: 'Package your dependencies into a Docker image and deploy Prefect Cloud execution layer to Google Compute Engine'
inputs:
  prefect_api_key:
    description: 'Prefect Cloud API key'
    required: true
  prefect_api_url:
    description: 'Prefect Cloud API URL'
    required: true
  artifact_repository:
    description: 'Artifact Registry Repository Name'
    required: false
    default: 'binance-transactions'
  image_name:
    description: 'Artifact Registry Image Name'
    required: false
    default: deployments
  region:
    description: 'GCP region'
    required: false
    default: 'us-central1'
  zone:
    description: 'GCP region with the zone'
    required: false
    default: 'us-central1-a'
  machine_type:
    description: 'GCP Compute Engine instance type'
    required: false
    default: 'e2-micro'
  machine_name:
    description: 'GCP Compute Engine instance name'
    required: false
    default: 'binance-transactions'
  dockerfile_path:
    description: 'Path and filename of the Dockerfile'
    required: false
    default: Dockerfile
  gcp_credentials_json:
    description: 'Content of the Service Account JSON key file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - id: set-image
      run: |
        echo "RAW_IMAGE=${{ inputs.region }}-docker.pkg.dev/$GCP_PROJECT/${{ inputs.artifact_repository }}/${{ inputs.image_name }}" >> $GITHUB_ENV
        echo "IMAGE_URI=${{ inputs.region }}-docker.pkg.dev/$GCP_PROJECT/${{ inputs.artifact_repository }}/${{ inputs.image_name }}:$GITHUB_SHA" >> $GITHUB_ENV
        echo "uri=$(echo $IMAGE_URI)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: '${{ inputs.region }}-docker.pkg.dev'
        username: _json_key
        password: ${{ inputs.gcp_credentials_json }}

    - id: build-image
      run: |
        docker build -q --build-arg PREFECT_API_KEY=${{ inputs.prefect_api_key }} --build-arg PREFECT_API_URL=${{ inputs.prefect_api_url }} -t "${{ env.RAW_IMAGE }}" -f ${{ inputs.dockerfile_path }} .
        docker tag "${{ env.RAW_IMAGE }}" "${{ env.IMAGE_URI }}"
        docker push "${{ env.RAW_IMAGE }}"
        docker push "${{ env.IMAGE_URI }}"
      shell: bash

    - id: terminate-if-exists
      run: gcloud compute instances delete "${{ inputs.machine_name }}" --zone "${{ inputs.zone }}" --quiet --verbosity=error
      continue-on-error: true
      shell: bash

    - id: deploy-vm
      name: Deploy Prefect Agent VM
      shell: bash
      run: |
        export EMAIL=$(cat $GOOGLE_GHA_CREDS_PATH | jq -r '.["client_email"]')
        gcloud compute instances create-with-container "${{ inputs.machine_name }}" \
          --zone "${{ inputs.zone }}" \
          --machine-type "${{ inputs.machine_type }}" \
          --service-account $EMAIL \
          --scopes "cloud-platform" \
          --container-image "${{ env.IMAGE_URI }}"
