name: 'Setup Infra'
branding:
  icon: cloud
  color: yellow
description: 'Package your dependencies into a Docker image and push it to Google Artifact Registry'
inputs:
  gcp_credentials_json:
    description: 'Content of the Service Account JSON key file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ inputs.gcp_credentials_json }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
