name: "Delete Setup"
on:
  workflow_dispatch:
    inputs:
      gcs_location:
        description: Location of the GCS bucket
        required: true
        default: "US"
        type: string
      bucket_suffix:
        description: Postfix for GCS bucket name
        required: true
        default: "raw-crypto-data"
        type: string
      dataset_name:
        description: BigQuery dataset name
        required: true
        default: "crypto_data"
        type: string
jobs:
  delete-gcp:
    name: Delete GCP services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: infra
        name: Destroy infrastructure
        uses: ./.github/actions/delete-infra
        with:
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          gcs_location: ${{ github.event.inputs.gcs_location }}
          bucket_suffix: ${{ github.event.inputs.bucket_suffix }}
          dataset_name: ${{ github.event.inputs.dataset_name }}


      
