name: Prefect Deployments CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'flows/**'

jobs:
  get-flows:
    runs-on: ubuntu-latest
    needs: create-blocks
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: set-matrix
        name: Collect Prefect flows
        run: echo "matrix=$(ls flows/*.py | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build-deployment:
    needs: get-flows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flows: ${{ fromJson(needs.build-flows.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: flow
        name: Build Prefect flows
        run: |
          export FLOW_NAME=$(basename ${{ matrix.flows }} .py)
          echo "entrypoint=${{ matrix.flows }}:$FLOW_NAME" >> $GITHUB_OUTPUT
      - id: deploy
        name: Setup Prefect deployment
        uses: ./.github/actions/deploy-flows
        with:
          prefect_api_key: ${{ secrets.PREFECT_API_KEY }}
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          flow_entrypoint: ${{ steps.flow.outputs.entrypoint }}
          deployment: ${{ github.event.inputs.deployment }} ||
          queue: ${{ github.event.inputs.queue }}
          github_block_name: github/${{ github.event.inputs.github_block_name }}
          cloudrun_block_name: cloud-run-job/${{ github.event.inputs.cloudrun_block_name }}
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          python_version: github/${{ github.event.inputs.python_version }}
          install_command: github/${{ github.event.inputs.install_command }}
