name: Prefect Deployments CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'flows/**'

jobs:
  build-flows:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: set-matrix
        run: echo "matrix=$(ls flows/*.py | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  deploy:
    needs: build-flows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flows: ${{ fromJson(needs.build-flows.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: flow  # example output: "flows/hello.py:hello"
        run: |
          export FLOW_NAME=$(basename ${{ matrix.flows }} .py)
          echo "entrypoint=${{ matrix.flows }}:$FLOW_NAME" >> $GITHUB_OUTPUT
      - id: deploy
        uses: ./.github/actions/deploy-flows
        with:
          prefect_api_key: ${{ secrets.PREFECT_API_KEY }}
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          flow_entrypoint: ${{ steps.flow.outputs.entrypoint }}
          deployment: "default" # optional
          queue: "default" # optional
          gcp_creds_block_name: "gcp-credentials/default" # optional
          github_block_name: "github/default" # optional
          cloudrun_block_name: "cloud-run-job/default" # optional
          python_version: "3.10" # optional
          install_command: "pip install ." # optional
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
