name: "Setup Infrastructure"
on:
  workflow_dispatch:
    inputs:
      region:
        description: GCP region
        required: true
        default: 'us-central1'
        type: string
      zone:
        description: Zone in the selected GCP region
        required: true
        default: 'us-central1-a'
        type: string
jobs:
  
  setup_gcp:
    name: Setup GCP services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: setup-infra
        name: Setup infra
        uses: ./.github/actions/build-infra
        with:
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          region: ${{ github.event.inputs.region }}
          zone: ${{ github.event.inputs.zone }}


      
