name: "Deploy Agent and Flows"
on:
  workflow_dispatch:
    inputs:
      region:
        description: GCP region
        required: true
        default: 'us-central1'
        type: string
      zone:
        description: Zone in the selected GCP region
        required: true
        default: 'us-central1-a'
        type: string
      artifact_repository:
        description: Artifact Registry Repository
        required: true
        default: "binance-transactions"
        type: string
      image_name:
        description: Artifact Container Name
        required: true
        default: 'deployments'
        type: string
      machine_type:
        description: GCP Compute Engine instance type
        required: true
        default: 'e2-micro'
        type: string
      gh_block_name:
        description: 'GitHub block name'
        required: false
        default: "default-gh"
        type: string
      crj_block_name:
        description: 'CloudRunJob block name'
        required: false
        default: "default-crj"
        type: string
      gcp_creds_block_name:
        description: 'Name of the GcpCredentials block'
        required: false
        default: "default-gcp"
        type: string
      deployment:
        description: 'Prefect deployment name'
        required: false
        default: "default-deployment"
        type: string
      queue:
        description: 'Prefect queue name'
        required: false
        default: "default-queue"
        type: string
  push:
    branches:
      - main
    paths:
      - 'flows/**'
jobs:
  deploy-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: deploy-container
        uses: ./.github/actions/deploy-container
        with:
          prefect_api_key: ${{ secrets.PREFECT_API_KEY }}
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          artifact_repository: ${{ github.event.inputs.artifact_repository }}  # optional
          region: ${{ github.event.inputs.region }}  # optional
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          # gcp_sa_email: ${{ secrets.GCP_SA_EMAIL }}
          zone: ${{ github.event.inputs.zone }}  # optional
          machine_type: ${{ github.event.inputs.machine_type }}  # optional

      - id: create-blocks
        uses: ./.github/actions/create-blocks
        with:
          prefect_api_key: ${{ secrets.PREFECT_API_KEY }}
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          image_uri: ${{ env.IMAGE_URI }}
          gh_block_name: ${{ github.event.inputs.gh_block_name }} # optional
          crj_block_name: ${{ github.event.inputs.crj_block_name }} # optional
          region: ${{ github.event.inputs.region }}  # optional

  build-flows:
    runs-on: ubuntu-latest
    needs: deploy-container
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "matrix=$(ls flows/*.py | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  deploy-flows:
    needs: build-flows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flows: ${{ fromJson(needs.build-flows.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - id: flow  # example output: "flows/hello.py:hello"
        run: |
          export FLOW_NAME=$(basename ${{ matrix.flows }} .py)
          echo "entrypoint=${{ matrix.flows }}:$FLOW_NAME" >> $GITHUB_OUTPUT
      - id: deploy
        uses: ./.github/actions/deploy-flows
        with:
          prefect_api_key: ${{ secrets.PREFECT_API_KEY }}
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          flow_entrypoint: ${{ steps.flow.outputs.entrypoint }}
          deployment: ${{ github.event.inputs.deployment }} # optional
          queue: ${{ github.event.inputs.queue }} # optional
          storage_block: github/${{ github.event.inputs.gh_block_name }} # optional
          infrastructure_block: cloud-run-job/${{ github.event.inputs.crj_block_name }} # optional
