name: "Setup Infrastructure"
on:
  workflow_dispatch:
    inputs:
      region:
        description: GCP region
        required: true
        default: 'us-central1'
        type: string
      zone:
        description: Zone in the selected GCP region
        required: true
        default: 'us-central1-a'
        type: string
jobs:
  setup_gcp:
    name: Setup GCP services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: infra
        name: Setup infra
        uses: ./.github/actions/setup-infra
        with:
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          gcs_location: ${{ github.event.inputs.gcs_location }}
          bucket_suffix: ${{ github.event.inputs.bucket_suffix }}
          dataset_name: ${{ github.event.inputs.dataset_name }}


      
